apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../deploy
  - access.yaml
  - controller.yaml
images:
  - name: cellbox-controller
    newName: registry.example.invalid/cellbox-controller
    newTag: v0.1.0
